### ISSUE TITLE
Allow extensions to add new conditions to logic shortcode

### ISSUE THREAD

**Issue by brashrebel** [brashrebel/render#63]
This may already be possible, I just don't know how. It is an example of something that would be nice to do. I was working with the EDD extension and thought the main logic shortcode could be enhanced by including commerce related conditions like `is_paying_customer()` and `is_on_sale()` (both fictional, I think but examples of what could be). The extension would probably be responsible for creating the functions and then adding them to the logic shortcode's selectbox options.

Generally speaking, it would be nice for extensions to modify and add to the shortcodes built into Render. Like adding specific custom fields to the Post Meta shortcode or something like that. I could make another issue as this one is getting off topic....but nah.

**Comment by joelworsham** [comment]
Every shortcode has its attributes passed through a filter before displaying. So in theory this should be possible. I'll look into it more though.

**Comment by brashrebel** [comment]
I was thinking it probably is possible. Just don't know how.

**Comment by joelworsham** [comment]
So in order to add more atts to the modal, you would want to use the filter `render_att_pre_loop`. Make sure to pass parameters in by calling it like so: `add_filter( 'render_att_pre_loop', 'function', 10, 3 );`

Then use the 2nd parameter (`code`) to tell when it's on the logic shortcode, and manually inject your new attributes into the array.

As for having them actually work in the shortcode callback, I'll need to edit it to allow this. I'll close the issue with the commit when it's done.

**Comment by joelworsham** [comment]
I've added a filter in the logic shortcode callback. It filters the arg1 result and also passes the atts. So you could call it like so: `add_filter( 'render_sc_logic_arg1', 'function', 10, 2 );`

The 2nd parameter (`$atts`) will contain the atts passed through the shortcode. So then you just need to perform another switch case, just like in the original callback, to check for your new conditions. If the current arg1 condition is one of your new conditions, perform then and return it, otherwise just pass the arg1 result back through.
